# Site
title: Mark Theis
description: >-
  I'm a systems software graduate student at UC Berkeley. I work with the NetSys
  Lab on internet protocol and architecture research advised by Scott Shenker.
  Broadly, I enjoy computers, networking, operating systems, and the underlying
  hardware that enables them.
permalink: /:categories/:title/

# Repository
git:
  repository_url: https://github.com/metheis/personal_site

# Navigation
nav:
  About:
    - text: Introduction
      url: /
      available: true
    - text: Academic Research
      url: /research/
      available: true
    - text: Interests and Skills
      url: /interests/
      available: true
  Resources:
    - text: External Links
      url: /external-links/
      available: true

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Build
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
exclude: ["README.md"]
